flowchart TB
    subgraph " "
    v12["Channel.fromPath"]
    v13["Channel.fromPath"]
    v14["Channel.fromPath"]
    v15["Channel.fromPath"]
    v16["Channel.fromPath"]
    v17["Channel.fromPath"]
    v18["Channel.fromPath"]
    v19["Channel.fromPath"]
    v20["Channel.fromPath"]
    end
    subgraph " "
    v21[" "]
    v33[" "]
    v37[" "]
    v38[" "]
    v46[" "]
    v52[" "]
    v53[" "]
    v79[" "]
    v80[" "]
    v84[" "]
    v85[" "]
    v113[" "]
    v138[" "]
    end
    v32([converter_capsule])
    v45([motion_correction])
    v51([movie_qc])
    v56([decrosstalk_split_json])
    v64([decrosstalk_roi_images])
    v69([extraction])
    v72([dff_capsule])
    v78([classifier])
    v83([oasis_event_detection])
    v112([ophys_nwb])
    v137([pipeline_processing_metadata_aggregator])
    v34(( ))
    v40(( ))
    v41(( ))
    v42(( ))
    v47(( ))
    v48(( ))
    v49(( ))
    v54(( ))
    v55(( ))
    v57(( ))
    v58(( ))
    v59(( ))
    v60(( ))
    v61(( ))
    v62(( ))
    v65(( ))
    v66(( ))
    v67(( ))
    v70(( ))
    v71(( ))
    v73(( ))
    v74(( ))
    v75(( ))
    v76(( ))
    v81(( ))
    v82(( ))
    v86(( ))
    v94(( ))
    v95(( ))
    v96(( ))
    v98(( ))
    v99(( ))
    v102(( ))
    v106(( ))
    v109(( ))
    v110(( ))
    v111(( ))
    v114(( ))
    v123(( ))
    v132(( ))
    v12 --> v32
    v13 --> v40
    v13 --> v48
    v13 --> v55
    v13 --> v58
    v13 --> v66
    v13 --> v71
    v13 --> v73
    v13 --> v82
    v13 --> v95
    v13 --> v132
    v14 --> v41
    v14 --> v59
    v14 --> v98
    v15 --> v94
    v16 --> v74
    v17 --> v62
    v17 --> v67
    v18 --> v76
    v19 --> v96
    v20 --> v21
    v32 --> v33
    v32 --> v34
    v32 --> v42
    v32 --> v49
    v32 --> v61
    v32 --> v114
    v32 --> v123
    v34 --> v37
    v34 --> v38
    v34 --> v45
    v40 --> v45
    v41 --> v45
    v42 --> v45
    v45 --> v46
    v45 --> v47
    v45 --> v54
    v45 --> v60
    v45 --> v86
    v45 --> v99
    v45 --> v114
    v45 --> v123
    v47 --> v51
    v48 --> v51
    v49 --> v51
    v51 --> v53
    v51 --> v52
    v51 --> v114
    v51 --> v123
    v54 --> v56
    v55 --> v56
    v56 --> v57
    v57 --> v64
    v58 --> v64
    v59 --> v64
    v60 --> v64
    v61 --> v64
    v62 --> v64
    v64 --> v65
    v64 --> v86
    v64 --> v102
    v64 --> v114
    v64 --> v123
    v65 --> v69
    v66 --> v69
    v67 --> v69
    v69 --> v70
    v69 --> v75
    v69 --> v86
    v69 --> v106
    v69 --> v114
    v69 --> v123
    v70 --> v72
    v71 --> v72
    v72 --> v81
    v72 --> v86
    v72 --> v110
    v72 --> v114
    v72 --> v123
    v73 --> v78
    v74 --> v78
    v75 --> v78
    v76 --> v78
    v78 --> v80
    v78 --> v79
    v78 --> v86
    v78 --> v109
    v78 --> v114
    v78 --> v123
    v81 --> v83
    v82 --> v83
    v83 --> v85
    v83 --> v84
    v83 --> v86
    v83 --> v111
    v83 --> v114
    v83 --> v123
    v86 --> v112
    v94 --> v112
    v95 --> v112
    v96 --> v112
    v98 --> v112
    v99 --> v112
    v102 --> v112
    v106 --> v112
    v109 --> v112
    v110 --> v112
    v111 --> v112
    v112 --> v113
    v112 --> v114
    v112 --> v123
    v114 --> v137
    v123 --> v137
    v132 --> v137
    v137 --> v138
