name: Add issue to Sci Comp and aind-physio-arch boards

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to Sci Comp triage board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/AllenNeuralDynamics/projects/155
          github-token: ${{ secrets.SERVICE_TOKEN }}
